#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-
# stub: kramdown-parser-gfm 1.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "kramdown-parser-gfm".freeze
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Thomas Leitner".freeze]
  s.date = "2019-05-29"
  s.email = "t_leitner@gmx.at".freeze
  s.files = ["CONTRIBUTERS".freeze, "COPYING".freeze, "VERSION".freeze, "lib/kramdown-parser-gfm.rb".freeze, "lib/kramdown/parser/gfm.rb".freeze, "lib/kramdown/parser/gfm/options.rb".freeze, "test/test_files.rb".freeze, "test/testcases/atx_header.html".freeze, "test/testcases/atx_header.text".freeze, "test/testcases/backticks_syntax.html".freeze, "test/testcases/backticks_syntax.options".freeze, "test/testcases/backticks_syntax.text".freeze, "test/testcases/codeblock_fenced.html".freeze, "test/testcases/codeblock_fenced.options".freeze, "test/testcases/codeblock_fenced.text".freeze, "test/testcases/hard_line_breaks.html".freeze, "test/testcases/hard_line_breaks.text".freeze, "test/testcases/hard_line_breaks_off.html".freeze, "test/testcases/hard_line_breaks_off.options".freeze, "test/testcases/hard_line_breaks_off.text".freeze, "test/testcases/header_ids.html".freeze, "test/testcases/header_ids.options".freeze, "test/testcases/header_ids.text".freeze, "test/testcases/header_ids_with_prefix.html".freeze, "test/testcases/header_ids_with_prefix.options".freeze, "test/testcases/header_ids_with_prefix.text".freeze, "test/testcases/no_typographic.html".freeze, "test/testcases/no_typographic.options".freeze, "test/testcases/no_typographic.text".freeze, "test/testcases/paragraph_end-disabled.html".freeze, "test/testcases/paragraph_end-disabled.options".freeze, "test/testcases/paragraph_end-disabled.text".freeze, "test/testcases/paragraph_end.html".freeze, "test/testcases/paragraph_end.text".freeze, "test/testcases/strikethrough.html".freeze, "test/testcases/strikethrough.text".freeze, "test/testcases/task_list.html".freeze, "test/testcases/task_list.text".freeze, "test/testcases/two_para_hard_line_breaks.html".freeze, "test/testcases/two_para_hard_line_breaks.text".freeze]
  s.homepage = "https://github.com/kramdown/parser-gfm".freeze
  s.licenses = ["MIT".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.3".freeze)
  s.rubygems_version = "3.1.2".freeze
  s.summary = "kramdown-parser-gfm provides a kramdown parser for the GFM dialect of Markdown".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<kramdown>.freeze, ["~> 2.0"])
  else
    s.add_dependency(%q<kramdown>.freeze, ["~> 2.0"])
  end
end
